
// default package
// Generated Feb 15, 2015 8:24:16 PM by Hibernate Tools 3.4.0.CR1
package com.trailshop.entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.CascadeType;



/**
 * Order generated by hbm2java
 */

@Entity
@Table(name="CartOrder")
public class CartOrder implements java.io.Serializable {

	@Id
	@GeneratedValue (strategy=GenerationType.IDENTITY)
	@Column(name="orderId")
	private long orderId;
	@Column(name="orderDate")

	private Date orderDate;
	@Column(name="orderStatus")

	private String orderStatus;
	@Column(name="totalCost")

	private Float totalCost;

	@Column(name="customeruniqueId")

	private String customeruniqueId;
	
	@OneToMany(mappedBy = "order")
	private List<OrderItem> orderItems = new ArrayList<OrderItem>(0);

	public List<OrderItem> getOrderItems() {
		return orderItems;
	}

	public void setOrderItems(List<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

	public CartOrder() {
	}

	public CartOrder(long orderId) {
		this.orderId = orderId;
	}

	public CartOrder(long orderId, Date orderDate, String orderStatus, Float totalCost, String customeruniqueId) {
		this.orderId = orderId;
		this.orderDate = orderDate;
		this.orderStatus = orderStatus;
		this.totalCost = totalCost;
		this.customeruniqueId = customeruniqueId;
	}

	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Float getTotalCost() {
		return this.totalCost;
	}

	public void setTotalCost(Float totalCost) {
		this.totalCost = totalCost;
	}

	public String getCustomeruniqueId() {
		return this.customeruniqueId;
	}

	public void setCustomeruniqueId(String customeruniqueId) {
		this.customeruniqueId = customeruniqueId;
	}
	
	

}
