
// default package
// Generated Feb 15, 2015 8:24:16 PM by Hibernate Tools 3.4.0.CR1

package com.trailshop.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;


/**
 * OrderItem generated by hbm2java
 */

@Entity
@Table(name="OrderItem")
public class OrderItem implements java.io.Serializable {

	@Id
	@GeneratedValue (strategy=GenerationType.IDENTITY)
	@Column(name="orderItemId" )
	private long orderItemId;
	
	@ManyToOne
	@JoinColumn(name="productId", nullable=false)
	private Product product;

	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne
	@JoinColumn(name="orderId", nullable=false)
	private CartOrder order;
	
	
	@Column(name="quantity")
	
	private Long quantity;
	
	
	

	public OrderItem() {
	}

	public OrderItem(long orderItemId) {
		this.orderItemId = orderItemId;
	}

	public OrderItem(long orderItemId, Product product, CartOrder order, Long quantity) {
		this.orderItemId = orderItemId;
		this.product = product;
		this.order = order;
		this.quantity = quantity;
	}

	public long getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(long orderItemId) {
		this.orderItemId = orderItemId;
	}

	public Product getProductId() {
		return this.product;
	}

	public void setProductId(Product product) {
		this.product = product;
	}

	public CartOrder getOrder() {
		return this.order;
	}

	public void setOrder(CartOrder order) {
		this.order = order;
	}

	public Long getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Long quantity) {
		this.quantity = quantity;
	}

}
