package com.trailshop.entities;

// default package
// Generated Feb 17, 2015 7:18:45 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */

@Entity
@Table(name="Product")
public class Product implements java.io.Serializable {

	@Id
	@Column(name="productId")
	private long productId;
	@Column(name="name")
	private String name;
	@Column(name="quantity")
	private Long quantity;
	@Column(name="status")
	private Integer status;
	@Column(name="unitPrice")
	private Float unitPrice;
	@Column(name="description")
	private String description;
	@Column(name="productUrl")
	private String productUrl;
	
	
	@OneToMany(mappedBy = "product")
	private List<OrderItem> orderItems = new ArrayList<OrderItem>(0);
	

	public List<OrderItem> getOrderItems() {
		return orderItems;
	}

	public void setOrderItems(List<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

	public Product() {
	}

	public Product(long productId) {
		this.productId = productId;
	}

	public Product(long productId, String name, Long quantity, Integer status, Float unitPrice, String description,
			String productUrl, Set orderItemsForProductId, Set orderItemsForProductProductId) {
		this.productId = productId;
		this.name = name;
		this.quantity = quantity;
		this.status = status;
		this.unitPrice = unitPrice;
		this.description = description;
		this.productUrl = productUrl;
		
	}

	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Long quantity) {
		this.quantity = quantity;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Float getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Float unitPrice) {
		this.unitPrice = unitPrice;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getProductUrl() {
		return this.productUrl;
	}

	public void setProductUrl(String productUrl) {
		this.productUrl = productUrl;
	}

	
}
